---
#
- name: Put into custom format for Mev-Geth's config.toml
  set_fact:
    geth_nat_ip: "{{geth_nat_prefix + geth_host_ip.split('.') }}"

- name: Create configuration directory
  file:
    path: "{{ geth_config_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_group }}"
    recurse: yes
  become: true

- name: Generate config file
  template:
    src: "{{ geth_config_template }}"
    dest: "{{ geth_config_dir }}/config.toml"
    owner: "{{ geth_user }}"
    group: "{{ geth_group }}"
    mode: 0644
  become: true
  register: config_toml

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    geth_state_updates: "{{ geth_state_updates + ['geth.config_toml'] }}"
  when: config_toml is changed

- name: Create data directory
  file:
    path: "{{ geth_data_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_group }}"
    recurse: yes
  become: true

- name: Init the database
  command: "{{geth_current_dir}}/geth init --datadir {{geth_data_dir}} {{geth_genesis_path}}"
  when: geth_init_database

