---
- name: Create Mev-Geth systemd service
  template:
    src: "{{ geth_systemd_template }}"
    dest: "{{ geth_systemd_dir }}/geth.service"
    owner: "root"
    group: "root"
  become: true
  when: ( geth_managed_service ) and
    ( ansible_os_family != "Darwin" )
  register: systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    geth_state_updates: "{{ geth_state_updates + ['geth.systemd_file'] }}"
  when: systemd_file is changed

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: systemd_file is changed

- name: Enable and start Geth service
  systemd:
    name: geth
    state: "{{ geth_systemd_state }}"
    enabled: true
  become: true
  when: ( geth_state_updates|length > 0 ) and
    ( geth_managed_service ) and
    ( ansible_os_family != "Darwin" )

# Darwin only
- name: Create Launchd service plist for Darwin
  template:
    src: "{{ geth_launchd_template }}"
    dest: "{{ geth_launchd_dir }}/org.ethereum.geth.plist"
  become: true
  when: ( ansible_os_family == "Darwin" ) and
    ( geth_managed_service )
